apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
  - deployment.yaml

configMapGenerator:
  - name: datalake-query-db-consumer-configmap
    literals:
      - DATALAKEQUERYDBCONSUMER_DB_URL=
      - DATALAKEQUERYDBCONSUMER_KAFKA_GROUP_ID=
      - DATALAKEQUERYDBCONSUMER_KAFKA_TOPIC=
      - KAFKA_BROKERS=